---
# proxmox-os.yml file of ansible-role bvierra.proxmoxserver
- name: Setup proxmox node system packages
  block:
    - name: Check for subscription apt repository
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/pve-enterprise.list
      when:
        - pve_no_subscription is true
      register: _pve_enterprise_list
    - name: Copy subscription repository to disabled file
      ansible.builtin.copy:
        remote_src: true
        src: /etc/apt/sources.list.d/pve-enterprise.list
        dest: /etc/apt/sources.list.d/pve-enterprise.list.dpkg-dist
        mode: "0600"
      when:
        - pve_no_subscription is true
        - _pve_enterprise_list.stat.exists is true
    - name: Remove subscription repository active file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent
      when:
        - pve_no_subscription is true
        - _pve_enterprise_list.stat.exists is true
    - name: Add an proxmox apt key
      ansible.builtin.apt_key:
        id: pve_no_subscription_apt_key_id
        url: pve_no_subscription_apt_key_url
        state: present
      when: pve_no_subscription is true
    - name: Add specified repository into sources list using specified filename
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        state: present
        filename: pve-no-subscription
        update_cache: true
      when: pve_no_subscription is true
    - name: Update proxmox node system packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
      cache_valid_time: 3600
      when: update_system_packages is true
    - name: Install additional packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: false
      loop: "{{ _pve_required_packages + pve_additional_packages | default([]) }}"
      when:
        - "'item' not in ansible_facts.packages"
    - name: Remove No-Subscription Nag Message
      ansible.builtin.replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: '\sExt.Msg.show\({'
        before: 'title: gettext\(.No valid subscription.\)'
        replace: " void({ //Ext.Msg.show({"
      notify: restart pveproxy
      when: pve_no_subscription is true
